name: 'Frontend Production Deploy'
# run-name: ${{}} Deploying

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
  push:


jobs:
  production_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testing Test
        run: echo "Hello World"
        run: echo ${{ }}

  production_deploy_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 2 Step'
        run: echo "Hello World 2"
        run: echo "Env = ${{ github.event.inputs.logLevel }}"
        run: echo "Env = ${{ github.event.inputs.tags }}"
        run: echo "Env = ${{ github.event.inputs.environment }}"

