name: 'Frontend Production Deploy'
# run-name: ${{}} Deploying

on:
  workflow_dispatch:

jobs:
  production_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Testing Test
        run: echo "Hello World"

  production_deploy_2:
    runs-on: ubuntu-latest
    steps:
      - name: 'Step 2 Step'
        run: |
          echo "Hello World 2"
          echo "Env = ${{ inputs.logLevel }}"
          echo "Env = ${{ inputs.tags }}"
          echo "Env = ${{ inputs.environment }}"

